#!/bin/bash
echo 'Syncing backend source files...'
mkdir -p "$(dirname '/srv/media/bleeparr/bleeparr_2_dev/bleeparr/backend/main.py')"
cp "/mnt/data/main.py" "/srv/media/bleeparr/bleeparr_2_dev/bleeparr/backend/main.py"
mkdir -p "$(dirname '/srv/media/bleeparr/bleeparr_2_dev/bleeparr/backend/tasks.py')"
cp "/mnt/data/tasks.py" "/srv/media/bleeparr/bleeparr_2_dev/bleeparr/backend/tasks.py"
mkdir -p "$(dirname '/srv/media/bleeparr/bleeparr_2_dev/bleeparr/backend/api/routes.py')"
cp "/mnt/data/routes.py" "/srv/media/bleeparr/bleeparr_2_dev/bleeparr/backend/api/routes.py"
mkdir -p "$(dirname '/srv/media/bleeparr/bleeparr_2_dev/bleeparr/backend/api/sonarr.py')"
cp "/mnt/data/sonarr.py" "/srv/media/bleeparr/bleeparr_2_dev/bleeparr/backend/api/sonarr.py"
mkdir -p "$(dirname '/srv/media/bleeparr/bleeparr_2_dev/bleeparr/backend/api/bleeparr_core.py')"
cp "/mnt/data/bleeparr_core.py" "/srv/media/bleeparr/bleeparr_2_dev/bleeparr/backend/api/bleeparr_core.py"
mkdir -p "$(dirname '/srv/media/bleeparr/bleeparr_2_dev/bleeparr/backend/db/models.py')"
cp "/mnt/data/models.py" "/srv/media/bleeparr/bleeparr_2_dev/bleeparr/backend/db/models.py"
mkdir -p "$(dirname '/srv/media/bleeparr/bleeparr_2_dev/bleeparr/backend/db/crud.py')"
cp "/mnt/data/crud.py" "/srv/media/bleeparr/bleeparr_2_dev/bleeparr/backend/db/crud.py"
