services:
  bleeparr:
    build: .
    network_mode: host
    ports:
      - "5050:5050"
    volumes:
      - ./bleeparr-1.1.py:/app/bleeparr-1.1.py
      - ./swears.txt:/app/swears.txt
      - ./videos:/app/videos
    environment:
      - SONARR_URL=http://10.20.30.60:8989
      - SONARR_API_KEY=e310542e0d0b474caacb58e941d3cc33
      - RADARR_URL=http://10.20.30.61:7878  # Add this line for Radarr URL
      - RADARR_API_KEY=975c911830dc45df849dc311a145667f  # Add this line for Radarr API key
      - UVICORN_PORT=5050
    restart: unless-stopped
