import { useCallback, useEffect, useState } from 'react';
import './App.css';
import Library from './Library';
import QualityControls from './QualityControls';
import QualitySummary from './QualitySummary';
import SpeechReadiness from './SpeechReadiness';
import Activity from './Activity';
import { jobActions } from './activityFilters';
import { processingHelp } from './processingHelp';

async function api(path, method = 'GET', body) {
  const response = await fetch(`/api${path}`, { method, headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${sessionStorage.getItem('bleeparr-token') || ''}` }, ...(body === undefined ? {} : { body: JSON.stringify(body) }) });
  const data = await response.json();
  if (!response.ok) throw new Error(typeof data.detail === 'string' ? data.detail : JSON.stringify(data.detail));
  return data;
}
const states = { review: 'Review required', skipped: 'Skipped · non-English audio', blocked: 'Blocked · folder access', queued: 'Queued', running: 'Processing', retry: 'Waiting to retry', failed: 'Needs attention', completed: 'Completed', no_matches: 'No matching words found' };

export default function App() {
  const [page, setPage] = useState('overview');
  const [status, setStatus] = useState({ jobs: [], counts: {}, events: [] });
  const [error, setError] = useState('');
  const [notice, setNotice] = useState('');
  const [busy, setBusy] = useState(false);
  const [token, setToken] = useState('');
  const [log, setLog] = useState(null);
  const refresh = useCallback(async () => { try { setStatus(await api('/status')); } catch (e) { setError(e.message); } }, []);
  useEffect(() => { refresh(); const timer = setInterval(refresh, 5000); return () => clearInterval(timer); }, [refresh]);
  async function action(fn, message = 'Saved') {
    setBusy(true); setError(''); setNotice('');
    try { const result = await fn(); setNotice(result?.message || message); await refresh(); return result; }
    catch (e) { setError(e.message); return null; }
    finally { setBusy(false); }
  }
  return <div className="shell">
    <aside><a href="#" className="brand" onClick={() => setPage('overview')}><span className="brand-icon"><img src="/bleeparr-icon.png" alt="" width="37" height="40"/></span> bleeparr<span className="brand-dot">.</span></a><p className="eyebrow">YOUR LIBRARY, CLEANER</p>
      <nav aria-label="Main navigation">{[['overview', '◫', 'Overview'], ['sonarr', '▣', 'TV shows'], ['radarr', '▤', 'Movies'], ['activity', '◷', 'Activity'], ['settings', '⚙', 'Settings']].map(([id, icon, label]) => <button key={id} className={page === id ? 'nav active' : 'nav'} onClick={() => { setPage(id); setNotice(''); }}><span aria-hidden="true">{icon}</span>{label}</button>)}</nav>
      <div className="aside-bottom"><span className="dot"/> Local processing · v3.0<p>Private by design.<br/>Made for your media library.</p></div>
    </aside>
    <main><header><div><p className="eyebrow">LIBRARY CONTROL CENTER</p><h1>{{ overview: 'A clearer picture.', sonarr: 'TV shows', radarr: 'Movies', activity: 'Processing activity', settings: 'Make it yours.' }[page]}</h1></div><span className="pill">{status.auto_process ? '● Monitoring enabled' : '○ Automatic monitoring paused'}</span></header>
      {error && <div className="alert error" role="alert">{error}<button onClick={() => setError('')} aria-label="Dismiss error">×</button></div>}
      {notice && <div className="alert success" role="status">{notice}</div>}
      {error.includes('token') && <form className="panel inline" onSubmit={e => { e.preventDefault(); sessionStorage.setItem('bleeparr-token', token); setError(''); refresh(); }}><label>Access token<input type="password" value={token} onChange={e => setToken(e.target.value)} /></label><button className="primary">Unlock</button></form>}
      {page === 'overview' && <>
        <div className="hero"><div><span className="tag">LESS FRICTION. MORE WATCHING.</span><h2>Your shows.<br/>A little more family friendly.</h2><p>Monitor the titles you choose. Bleeparr finds dialogue to censor, creates a cleaned copy, and keeps you informed.</p><button className="primary" onClick={() => setPage('sonarr')}>Choose what to monitor <span>→</span></button></div><div className="wave" aria-hidden="true">{[20,35,60,40,85,120,70,145,95,55,120,155,110,65,90,130,80,45,70,40,25].map((h,i) => <i key={i} style={{height:h}} />)}<span>THE SAME STORY. LESS NOISE.</span></div></div>
        <div className="stats">{[['completed', 'Cleaned files', 'Ready for your output library'], ['running', 'Processing now', 'One file at a time'], ['queued', 'In the queue', 'Ready when the worker is'], ['failed', 'Need attention', 'Clear reasons. Useful next steps.']].map(([key,title,detail]) => <div className="stat" key={key}><span>{title}</span><strong>{(status.counts[key] || 0) + (key === 'failed' ? (status.counts.blocked || 0) + (status.counts.review || 0) : 0)}</strong><small>{detail}</small></div>)}</div>
        <div className="section-head"><h2>Recent activity</h2><button onClick={() => setPage('activity')}>View all activity →</button></div>
        <Jobs jobs={status.jobs.slice(0,5)} busy={busy} action={action} setLog={setLog} blocklistEnabled={status.auto_blocklist}/>
        <p className="footnote">Censorship follows the available subtitles. Missing or inaccurate subtitles can leave dialogue uncensored. Your cleaned-file policy controls whether originals are retained.</p>
      </>}
      {(page === 'sonarr' || page === 'radarr') && <Library key={page} kind={page} api={api} action={action} busy={busy} Discover={Discover}/>}
      {page === 'activity' && <Activity status={status} states={states} jobsComponent={Jobs} busy={busy} action={action} setLog={setLog} scan={()=>action(()=>api('/scan','POST'),'Monitored library scanned')}/>}
      {page === 'settings' && <Settings action={action} busy={busy}/>}
      {log !== null && <div className="modal-backdrop"><section role="dialog" aria-modal="true" aria-label="Processing log" className="modal"><div className="section-head"><h2>Processing log</h2><button autoFocus onClick={() => setLog(null)}>Close</button></div><p>{log.title}</p><ResultSummary result={log.result}/>{processingHelp(log.result) && <FailureHelp result={log.result}/>}<details open={!processingHelp(log.result)}><summary>Technical details</summary><pre>{log.text}</pre></details></section></div>}
    </main>
  </div>;
}

function FailureHelp({result}) {
  const help = processingHelp(result);
  return <div className="failure-help"><h3>What happened</h3><p><strong>{help.title}</strong></p><p>{help.explanation}</p><h3>What to do next</h3><ol>{help.steps.map(step => <li key={step}>{step}</li>)}</ol><small>Error category: {help.code}</small></div>;
}

function ResultSummary({result = {}}) {
  if (result.outcome === 'skipped_language') return <section className="panel"><h3>Skipped · non-English audio</h3><p>{result.message}</p></section>;
  if (!result.subtitle_file) return <QualitySummary result={result}/>;
  const coverage = result.subtitle_coverage;
  const time = seconds => `${Math.floor(seconds / 60)}:${String(Math.floor(seconds % 60)).padStart(2, '0')}`;
  return <><QualitySummary result={result}/><section className="panel"><h3>Subtitle details</h3>
    <p>{result.subtitle_source || 'Selected file'}: {result.subtitle_file}{result.subtitle_stream_index != null && ` · stream ${result.subtitle_stream_index}`}{result.subtitle_track_title && ` · ${result.subtitle_track_title}`}</p>
    <p>Declared language: {result.subtitle_declared_language || 'unknown'} · detected: {result.subtitle_language || 'not enough text to determine'}</p>
    <p>{result.subtitle_cues ?? 0} cues · {result.subtitle_words ?? 0} subtitle words</p>
    {coverage && <><p>Dialogue from {time(coverage.first_cue_seconds)} to {time(coverage.last_cue_seconds)} of {time(coverage.duration_seconds)} · largest internal gap: {time(coverage.largest_gap_seconds)}</p>{coverage.warnings?.length > 0 && <ul>{coverage.warnings.map(warning => <li key={warning}>{warning}</li>)}</ul>}<p className="help">Timing checks can flag quiet scenes or long credits. Passing these checks does not prove every spoken line is present.</p></>}
    {result.matched_word_count != null && <p>{result.matched_word_count} configured words across {result.matched_occurrences} word/phrase matches · {result.merged_mute_count ?? result.mute_count ?? 0} mute intervals · {result.fallback_sections ?? 0} full-cue fallback sections</p>}
    {result.fallback_sections > 0 && <p className="help">Full-cue fallback also mutes surrounding dialogue; the matched-word count is based on subtitles.</p>}
    {result.outcome === 'no_matches_found' && <p><strong>{result.message || 'No matching words found; no cleaned output was created.'}</strong></p>}
  </section></>;
}

function Jobs({ jobs, busy, action, setLog, blocklistEnabled }) {
  const [reprocess, setReprocess] = useState(null);
  const [mutingReview,setMutingReview] = useState(null);
  if (!jobs.length) return <div className="empty"><span>✓</span><h3>A fresh start.</h3><p>Connect Sonarr or Radarr in Settings, choose your titles, then queue your first file.</p></div>;
  return <><div className="table-wrap"><table><thead><tr><th>Title</th><th>Status</th><th>Attempts</th><th>Actions</th></tr></thead><tbody>{jobs.map(job => <tr key={job.id}><td><strong>{job.title}</strong><small>{processingHelp(job.result)?.title || job.result.message || (job.result.output_path ? `Saved to ${job.result.output_path}` : job.path)}</small></td><td><span className={`badge ${job.status}`}>{states[job.status]}</span></td><td>{job.attempts}</td><td className="actions"><button disabled={busy} onClick={() => action(async () => { const data = await api(`/jobs/${job.id}/log`); setLog({text:data.log, result:job.result, title:job.title}); }, 'Log opened')}>Log</button>{job.status === 'completed' && job.item_id > 0 && <button disabled={busy} onClick={() => action(async () => { const preview = await api(`/jobs/${job.id}/reprocess-preview`); setReprocess({ ...preview, jobId: job.id }); }, 'Reprocessing preview opened')}>Reprocess</button>}{jobActions(job, blocklistEnabled).includes('review') && <button disabled={busy} onClick={()=>setMutingReview(job)}>Review muting</button>}{jobActions(job, blocklistEnabled).includes('retry') && <button disabled={busy} onClick={() => action(() => api(`/jobs/${job.id}/retry`, 'POST'), 'Retry queued')}>Retry</button>}{jobActions(job, blocklistEnabled).includes('search') && <button disabled={busy} onClick={() => action(() => api(`/jobs/${job.id}/search`, 'POST'))}>Search releases</button>}{jobActions(job, blocklistEnabled).includes('search') && <><button disabled={busy} onClick={() => action(async () => {const result=await api(`/jobs/${job.id}/replacement-preview`); return {message:`Matched release: ${result.release}. No changes made.`};})}>Check release match</button>{jobActions(job, blocklistEnabled).includes('replace') && <button disabled={busy} onClick={() => action(() => api(`/jobs/${job.id}/replacement`, 'POST'))}>Blocklist & search</button>}</>}</td></tr>)}</tbody></table></div>
    {mutingReview && <div className="modal-backdrop"><section role="dialog" aria-modal="true" aria-label="Review planned muting" className="modal"><div className="section-head"><h2>Review {mutingReview.title}</h2><button autoFocus disabled={busy} onClick={()=>setMutingReview(null)}>Close</button></div><p>No cleaned output has been published. Review these planned mutes and subtitle timing before approving broader silence.</p><QualitySummary result={mutingReview.result}/><button className="primary" disabled={busy} onClick={()=>action(async()=>{const result=await api(`/jobs/${mutingReview.id}/approve-muting`,'POST',{token:mutingReview.result.review_token});setMutingReview(null);return result;})}>Approve this muting plan</button><p className="help">Approval does not bypass title or timing checks. A changed source, subtitle, setting, or mute plan requires a new review.</p></section></div>}
    {reprocess && <div className="modal-backdrop"><section role="dialog" aria-modal="true" aria-label="Reprocess file" className="modal"><div className="section-head"><h2>Reprocess {reprocess.title}</h2><button autoFocus disabled={busy} onClick={() => setReprocess(null)}>Close</button></div><p>{reprocess.reason}</p><p>Current file: {reprocess.source}</p>{reprocess.retained_original && <p>Using the retained unmuted original.</p>}{reprocess.eligible && <><p>English audio stream {reprocess.audio_stream} · {reprocess.subtitle_cues} subtitle cues · detected language: {reprocess.subtitle_language}</p><p>Selected subtitles: {reprocess.subtitle_file} · {reprocess.matched_word_count} matching words</p><button className="primary" disabled={busy} onClick={() => action(async () => { const result = await api(`/jobs/${reprocess.jobId}/reprocess`, 'POST', { fingerprint: reprocess.fingerprint }); setReprocess(null); return result; })}>Queue this file</button></>}</section></div>}
  </>;
}

function Discover({kind, action, busy, onAdded}) {
  const [term, setTerm] = useState(''); const [results, setResults] = useState([]); const [options, setOptions] = useState({profiles:[],roots:[]});
  const [profile, setProfile] = useState(''); const [root, setRoot] = useState(''); const [search, setSearch] = useState(false);
  return <div className="panel"><h2>Find something to watch</h2><p>Titles are added to {kind === 'sonarr' ? 'Sonarr' : 'Radarr'} and monitored by Bleeparr.</p><form className="inline" onSubmit={e => {e.preventDefault(); action(async () => { const [found, opts] = await Promise.all([api(`/discover/${kind}?term=${encodeURIComponent(term)}`), api(`/options/${kind}`)]); setResults(found); setOptions(opts); setProfile(String(opts.profiles[0]?.id || '')); setRoot(opts.roots[0]?.path || ''); }, 'Search complete');}}><label>Title<input required minLength={2} value={term} onChange={e => setTerm(e.target.value)}/></label><button className="primary" disabled={busy}>Search</button></form>
    {results.length > 0 && <><div className="form-grid"><label>Quality profile<select value={profile} onChange={e => setProfile(e.target.value)}>{options.profiles.map(p => <option value={p.id} key={p.id}>{p.name}</option>)}</select></label><label>Root folder<select value={root} onChange={e => setRoot(e.target.value)}>{options.roots.map(r => <option key={r.path}>{r.path}</option>)}</select></label></div><label className="check"><input type="checkbox" checked={search} onChange={e => setSearch(e.target.checked)}/> Start searching for downloads when added</label>{results.map(r => <div className="search-result" key={r.external_id}><div><h3>{r.title} <small>({r.year})</small></h3><p>{r.overview}</p></div><button disabled={busy || !root || !profile} onClick={() => action(async () => { const added = await api(`/discover/${kind}`, 'POST', {external_id:r.external_id, quality_profile_id:Number(profile), root_folder:root, search}); onAdded(); return added; }, 'Title added and monitored')}>Add & monitor</button></div>)}</>}
  </div>;
}

function Settings({action, busy}) {
  const [config, setConfig] = useState(null); const [error,setError] = useState(''); const [plexLibraries, setPlexLibraries] = useState([]); const [rulePreview, setRulePreview] = useState(null);
  useEffect(() => { api('/settings').then(setConfig).catch(e => setError(e.message)); }, []);
  function field(key, value) { setConfig(c => ({...c,[key]:value})); }
  if (!config) return <p>{error || 'Loading settings…'}</p>;
  async function save() { const payload = {...config}; delete payload.sonarr_key_configured; delete payload.radarr_key_configured; delete payload.plex_token_configured; delete payload.smtp_password_configured; return api('/settings','PUT',payload); }
  return <form onSubmit={e => {e.preventDefault(); action(save, 'Settings saved');}}>
    <div className="section-head"><p>Connections, processing, and the words you want to leave out.</p><button className="primary" disabled={busy}>Save settings</button></div>
    <div className="settings-grid">{['sonarr','radarr'].map(kind => <section className="panel" key={kind}><h2>{kind === 'sonarr' ? 'Sonarr · TV shows' : 'Radarr · Movies'}</h2><label>Server URL<input type="url" placeholder={`http://${kind}:8989`} value={config[kind+'_url']} onChange={e => field(kind+'_url', e.target.value)}/></label><label>API key<input type="password" placeholder={config[kind+'_key_configured'] ? 'Saved · leave blank to keep' : 'Paste API key'} value={config[kind+'_api_key']} onChange={e => field(kind+'_api_key',e.target.value)}/></label><details><summary>Media path mapping</summary><p>Translate the path reported by your media manager to the folder mounted in Bleeparr.</p><label>Manager path prefix<input placeholder="/srv/media/selected" value={config[kind+'_path_from']} onChange={e => field(kind+'_path_from',e.target.value)}/></label><label>Bleeparr path prefix<input placeholder="/media" value={config[kind+'_path_to']} onChange={e => field(kind+'_path_to',e.target.value)}/></label></details><button type="button" disabled={busy} onClick={() => action(async () => {await save(); return api(`/connections/${kind}/test`,'POST');}, 'Connection successful')}>Save & test connection</button></section>)}</div>
    <section className="panel"><h2>Notifications</h2><p>Receive email when processing finishes or needs your attention. Delivery problems never interrupt media processing.</p>
      <label className="check"><input type="checkbox" checked={config.email_enabled} onChange={e => field('email_enabled',e.target.checked)}/> Enable email notifications</label>
      <div className="form-grid"><div><h3>Notify me when</h3>{[['notify_completed','Processing completes'],['notify_failed','Processing fails or exhausts its retries'],['notify_retry','A processing retry is scheduled']].map(([key,label]) => <label className="check" key={key}><input type="checkbox" checked={config[key]} onChange={e => field(key,e.target.checked)}/>{label}</label>)}</div><div><label>Recipient email<input type="email" placeholder="you@example.com" value={config.smtp_to} onChange={e => field('smtp_to',e.target.value)}/></label><label>Sender email<input type="email" placeholder="bleeparr@example.com" value={config.smtp_from} onChange={e => field('smtp_from',e.target.value)}/></label></div></div>
      <div className="form-grid"><label>SMTP host<input placeholder="smtp.example.com" value={config.smtp_host} onChange={e => field('smtp_host',e.target.value)}/></label><label>SMTP port<input type="number" min="1" max="65535" value={config.smtp_port} onChange={e => field('smtp_port',Number(e.target.value))}/></label><label>Connection security<select value={config.smtp_security} onChange={e => field('smtp_security',e.target.value)}><option value="starttls">STARTTLS · usually port 587</option><option value="ssl">TLS · usually port 465</option><option value="none">Unencrypted · trusted local relay only</option></select></label><label>SMTP username<input autoComplete="off" value={config.smtp_username} onChange={e => field('smtp_username',e.target.value)}/></label><label>SMTP password or app password<input type="password" autoComplete="new-password" placeholder={config.smtp_password_configured ? 'Saved · leave blank to keep' : 'Enter password if required'} value={config.smtp_password} onChange={e => field('smtp_password',e.target.value)}/></label></div>
      <p className="help">Retry alerts are off by default. Emails include the title, outcome and summary—not full logs. If a delivery outcome is uncertain, automatic resending stops to avoid duplicate messages.</p>
      <button type="button" disabled={busy || !config.email_enabled} onClick={() => action(async () => { await save(); return api('/notifications/test','POST'); })}>Save & send test email</button>
      <NotificationHistory action={action} busy={busy}/>
    </section>
    <section className="panel"><h2>Plex synopsis notes</h2><p>Add a note to Plex after a cleaned movie or episode is available in your library. Your existing synopsis is preserved.</p>
      <div className="form-grid"><label>Plex server URL<input type="url" placeholder="http://plex:32400" value={config.plex_url} onChange={e => field('plex_url', e.target.value)}/></label><label>Plex token<input type="password" autoComplete="off" placeholder={config.plex_token_configured ? 'Saved · leave blank to keep' : 'Paste Plex token'} value={config.plex_token} onChange={e => field('plex_token', e.target.value)}/></label></div>
      <button type="button" disabled={busy} onClick={() => action(async () => { await save(); const result = await api('/plex/test', 'POST'); setPlexLibraries(result.libraries); return result; })}>Save & test Plex connection</button>
      <div className="form-grid"><div><h3>Libraries to update</h3>{plexLibraries.length ? plexLibraries.map(library => <label className="check" key={library.id}><input type="checkbox" checked={config.plex_libraries.includes(Number(library.id))} onChange={e => field('plex_libraries', e.target.checked ? [...config.plex_libraries, Number(library.id)] : config.plex_libraries.filter(id => id !== Number(library.id)))}/>{library.title}</label>) : <p>{config.plex_libraries.length ? `Saved library IDs: ${config.plex_libraries.join(', ')}. Test the connection to choose by name.` : 'Test the connection to choose your Plex libraries.'}</p>}</div><div><label>Movie and episode note<input value={config.plex_note} maxLength={300} onChange={e => field('plex_note',e.target.value)}/></label><label>Series note<input value={config.plex_series_note} maxLength={300} onChange={e => field('plex_series_note',e.target.value)}/></label></div></div>
      <label className="check"><input type="checkbox" checked={config.plex_series_note_enabled} onChange={e => field('plex_series_note_enabled', e.target.checked)}/> Also add a series note when it contains a cleaned episode</label>
      <details><summary>Cleaned-file path mapping</summary><p>If Plex sees your output folder under a different path, enter both prefixes below.</p><div className="form-grid"><label>Bleeparr output prefix<input placeholder="/output" value={config.plex_path_from} onChange={e => field('plex_path_from',e.target.value)}/></label><label>Output prefix seen by Plex<input placeholder="/srv/media/cleaned" value={config.plex_path_to} onChange={e => field('plex_path_to',e.target.value)}/></label></div></details>
      <label className="check"><input type="checkbox" checked={config.plex_enabled} onChange={e => field('plex_enabled',e.target.checked)}/> Automatically update Plex synopses after successful processing</label><p className="help">Plex must first index the cleaned output. Updates are checked every five minutes and retried up to 12 times. Only verified completed outputs are marked; mixed original/cleaned versions are skipped. Disabling this option stops future updates and keeps existing notes.</p>
      <button type="button" disabled={busy || !config.plex_enabled} onClick={() => action(async () => { await save(); return api('/plex/sync', 'POST'); })}>Save & sync Plex now</button>
    </section>
    <section className="panel"><h2>Automatic selection · CleanVid</h2>
      <label className="check"><input type="checkbox" checked={config.cleanvid_enabled || false} onChange={e => {field('cleanvid_enabled',e.target.checked); setRulePreview(null);}}/> Automatically monitor titles in CleanVid folders</label>
      <label>CleanVid folders as seen by Sonarr and Radarr<textarea rows="3" value={config.cleanvid_roots || ''} onChange={e => {field('cleanvid_roots',e.target.value); setRulePreview(null);}} placeholder="/srv/media/selected"/></label>
      <p className="help">One folder per line. Matching includes subfolders, using the title's path in Sonarr or Radarr. Existing titles and future requests qualify, even before their files download. Uncheck a title in the library to exclude it. Manually selected titles remain monitored outside these folders.</p>
      <p>Automatic queuing under Processing controls scheduled processing. With queuing paused, you can review matches without starting jobs. Enabling queuing or using Scan monitored titles includes existing files, not just new downloads.</p>
      <button type="button" disabled={busy} onClick={() => action(async () => {await save(); const result = await api('/monitoring/preview'); setRulePreview(result); return {message:'Selection preview loaded.'};})}>Save & preview matching titles</button>
      {rulePreview && <div><p>{rulePreview.items.filter(i => i.monitoring_source !== 'excluded').length} selected titles · {rulePreview.items.filter(i => i.monitoring_source === 'excluded').length} excluded · Processing {rulePreview.auto_process ? 'enabled' : 'paused'}</p>{rulePreview.errors.map(message => <p role="alert" key={message}>{message}</p>)}<ul>{rulePreview.items.slice(0,20).map(item => <li key={`${item.kind}-${item.id}`}>{item.title} · {item.kind === 'sonarr' ? 'TV' : 'Movie'}{item.monitoring_source === 'excluded' ? ' · excluded' : ''}</li>)}</ul>{rulePreview.items.length > 20 && <p>Showing the first 20 matches. Use TV shows or Movies to review individual titles.</p>}</div>}
    </section>
    <section className="panel"><h2>Cleaned files</h2><label>After processing<select value={config.output_mode || 'separate'} onChange={e => field('output_mode', e.target.value)}><option value="separate">Save in a separate folder · keep original</option><option value="alongside">Save beside the original · keep both</option><option value="replace">Replace the original · follow retention policy</option></select></label>
      {(config.output_mode || 'separate') === 'separate' && <label>Separate output folder<input placeholder="Default output folder (/output in Docker)" value={config.output_directory || ''} onChange={e => field('output_directory',e.target.value)}/><span className="help">Leave blank for the configured output folder, or choose a folder inside it. Your Docker output mount determines its location on your server.</span></label>}
      {config.output_mode === 'alongside' && <p>The cleaned copy is saved in the same folder with “(profanity removed)” in its name. The original is kept.</p>}
      {config.output_mode === 'replace' && <p>The original is removed only after the cleaned file passes full playback validation. The cleaned MKV uses the original name plus “(profanity removed)”; an old Bleeparr tag is replaced. Temporary originals are retained only when that option is enabled below.</p>}
      <p className="help">Same-folder and replacement modes need write access to your media folders. Existing destination files are never overwritten, except the selected original in replacement mode. Changes apply when the next job starts; completed files are not automatically reprocessed.</p>
    </section>
    <QualityControls config={config} field={field} api={api}/>
    <SpeechReadiness api={api} action={action} busy={busy} save={save}/>
    <section className="panel"><h2>Processing</h2><label className="check"><input type="checkbox" checked={config.auto_process} onChange={e => field('auto_process',e.target.checked)}/> Automatically queue available files from monitored titles</label><div className="form-grid"><label>Detection strategy<select value={config.bleeptool} onChange={e => field('bleeptool',e.target.value)}><option value="S-FSM">Small model + subtitle fallback</option><option value="S-M-FSM">Small + medium + subtitle fallback · recommended</option><option value="S-M">Small + medium · stop if words remain unresolved</option><option value="FSM">Subtitles only · fastest, broader muting</option></select></label><label>CPU threads<input type="number" min="1" max="32" value={config.cpu_threads} onChange={e => field('cpu_threads',Number(e.target.value))}/></label><label>Primary model<input value={config.model} onChange={e => field('model',e.target.value)}/></label><label>Fallback model<input value={config.fallback_model} onChange={e => field('fallback_model',e.target.value)}/></label><label>Scan interval (seconds)<input type="number" min="60" value={config.poll_seconds} onChange={e => field('poll_seconds',Number(e.target.value))}/></label><label>Maximum attempts<input type="number" min="1" max="10" value={config.max_attempts} onChange={e => field('max_attempts',Number(e.target.value))}/></label><label>Initial retry delay (minutes)<input type="number" min="1" value={config.retry_minutes} onChange={e => field('retry_minutes',Number(e.target.value))}/></label></div><label className="check"><input type="checkbox" checked={config.auto_search} onChange={e => field('auto_search',e.target.checked)}/> Request a manager search after an invalid-media failure</label><p className="help">At most one search per title every 24 hours by default. Existing files are retained. Sonarr/Radarr quality rules may prevent a replacement; this does not automatically blocklist a release.</p></section>
    <section className="panel"><h2>Damaged-file recovery</h2>
      <label className="check"><input type="checkbox" checked={config.auto_blocklist || false} onChange={e => field('auto_blocklist',e.target.checked)}/> Automatically blocklist damaged releases and search for replacements</label>
      <p>For damaged-media failures only. Bleeparr verifies the current file against its import and download history, then asks Sonarr or Radarr to mark that release as failed and search again. Memory, subtitle, storage, and permission failures do not trigger blocklisting.</p>
      <div className="form-grid"><label>Minimum hours between replacement searches<input type="number" min="24" max="720" value={config.replacement_cooldown_hours} onChange={e=>field('replacement_cooldown_hours',Number(e.target.value))}/></label><label>Maximum replacements per movie or episode in 30 days<input type="number" min="1" max="10" value={config.replacement_limit || 3} onChange={e=>field('replacement_limit',Number(e.target.value))}/></label></div>
      <p className="help">The current file is retained. Your manager’s quality rules and release availability still apply. Shared episode files, season packs, and uncertain history are skipped for review. A download is requested at most once; uncertain network outcomes stop automatic resending. This option takes priority over search-only recovery.</p>
      <p>Applies to future failures. For an existing failed job, use “Check release match” in Activity, then “Blocklist & search” once this option is enabled. Results and skipped reasons appear in System events.</p>
    </section>
    <section className="panel"><h2>Your words & phrases</h2><p>One word or phrase per line. For example, eat my shorts matches the full phrase, not its individual words. Matching ignores capitalization and punctuation within a subtitle cue.</p><label>Words and phrases to censor<textarea rows="8" value={config.swears} onChange={e => field('swears',e.target.value)}/></label></section>
    <button className="primary" disabled={busy}>Save settings</button>
  </form>;
}


function NotificationHistory({action,busy}) {
  const [data,setData] = useState({items:[],worker_enabled:true});
  const [error,setError] = useState('');
  const load=useCallback(async()=>{try{setData(await api('/notifications'));setError('');}catch(e){setError(e.message);}},[]);
  useEffect(()=>{load();const timer=setInterval(load,5000);return()=>clearInterval(timer);},[load]);
  const labels={pending:'Waiting to send',sending:'Sending',sent:'Accepted by mail server',failed:'Delivery failed',unknown:'Delivery uncertain'};
  return <><h3>Email delivery history</h3>{!data.worker_enabled && <p className="help">Sending is paused in this local preview.</p>}{error && <p role="alert">{error}</p>}{!data.items.length ? <p>No email notifications yet.</p> : <div className="table-wrap"><table><thead><tr><th>Notification</th><th>Delivery</th><th>Actions</th></tr></thead><tbody>{data.items.map(item=><tr key={item.id}><td>{item.subject}<small>{item.recipient} · {new Date(item.created*1000).toLocaleString()}</small></td><td>{labels[item.status]}<small>{item.error}</small></td><td>{['failed','unknown'].includes(item.status) && <button type="button" disabled={busy} onClick={()=>action(async()=>{const result=await api(`/notifications/${item.id}/retry`,'POST');await load();return result;})}>{item.status==='unknown'?'Resend (may duplicate)':'Retry email'}</button>}</td></tr>)}</tbody></table></div>}</>;
}
