export function processingHelp(result = {}) {
  if (!result.error && !result.error_code) return null;
  const code = result.error_code || 'unknown';
  const detail = (result.error || '').toLowerCase();
  const help = (title, explanation, steps) => ({ title, explanation, steps, code });
  if (code==='muting_review') return help('The planned mutes need review.', 'Speech recognition left unusually broad silence. No cleaned output was published.', ['Open Review muting to see the planned duration and fallback count. Check the subtitles and audio before approving.', 'Approval applies only to this unchanged muting plan. Fix subtitles and Retry if the silence looks excessive.']);
  if (code==='subtitle_alignment_review') return help('Subtitle timing could not be confirmed.', 'Sampled subtitle dialogue did not reliably match speech at those timestamps. No output was published.', ['Supply subtitles matching this release and cut, then Retry. Quiet scenes or transcription uncertainty can also need review.']);
  if (code==='title_review') return help('The download may be the wrong title or cut.', 'Internal title, episode, year, or runtime details conflict with the selected library item. No output was published.', ['Check the release in Sonarr or Radarr and obtain the correct copy if needed. Inspect alternate titles or an extended cut before changing the title-check setting.']);
  if (code==='original_storage_full') return help('The original archive needs space.', 'Retention is enabled, but the archive cannot hold this original. The original remains in place and no replacement was published.', ['Wait for retained originals to expire, increase the archive limit, or disable retention deliberately. Blocked replacements are checked again during automatic scans.']);
  if (code === 'output_unwritable' || (code === 'output_configuration' && /not writable/.test(detail))) return help('The destination folder is read-only or not writable.', 'This is a folder-access problem, not evidence of damaged media. Replacement and same-folder output require write access.', ['Make the media mount writable, or choose a writable separate output folder. Blocked jobs are checked again during automatic scans after access is fixed; you can also use Retry.']);
  if (code === 'video_missing' || /stream map '0:v:0' matches no streams/.test(detail)) return help('This file has no readable video stream.', 'The file may contain audio only even though its name ends in .mkv. Repeating speech recognition cannot restore missing video.', ['Obtain a complete video copy through your media manager, then process the new file. Check the release history before blocklisting: an older cleaner may have damaged this copy.']);
  if (code === 'processing' && /error initializing complex filters/.test(detail) && /cannot allocate memory/.test(detail)) return help('FFmpeg could not build the censor filter.', 'Long lists of censor intervals can exceed the filter parser’s limits. This message does not necessarily mean the container ran out of memory.', ['The updated Bleeparr builds balanced filter expressions for long files. Retry this job with the updated version.']);
  if (code === 'invalid_media') {
    const damagedContainer = /exceeds containing master|ebml/.test(detail);
    const timing = /non[- ]monotonous dts|non[- ]monotonic/.test(detail);
    return help('The video file could not be read reliably.',
      damagedContainer ? `The MKV container has inconsistent internal data${timing ? ', and the video timestamps jump backward' : ''}. This usually means the file is damaged or malformed. FFmpeg stopped rather than produce an unreliable cleaned copy.` : 'The media reader found invalid video or container data. This can happen with a damaged, incomplete, or malformed file; the log does not establish how it became damaged.',
      ['Check that the download has finished. If it has, obtain a different release through Sonarr or Radarr.', '“Search releases” asks your media manager to search, but its quality rules may prevent a replacement. It does not delete or blocklist the current release.', 'After a replacement downloads, a monitored title will be picked up by automatic scanning when enabled. Retrying the unchanged file will usually fail again.']);
  }
  if (code === 'out_of_memory') return help('Processing ran out of memory.', 'The worker was killed while its container reported a memory shortage.', ['Increase the memory allowance or choose a smaller speech model, then retry. A different video release or Hugging Face token will not solve a memory limit.']);
  if (code === 'speech_model_missing') return help('A local speech model is missing.', 'Offline processing could not find all the files for the selected model.', ['Restore or deliberately download the selected model into the persistent model folder during setup, then retry. Processing will not download models automatically.']);
  if (code === 'speech_model') return help('Speech recognition could not finish.', 'A speech model or its dependencies failed. Full-subtitle fallback was blocked and no cleaned output was created.', ['Check the speech-model error in Technical details. Repair the local model cache or install the compatible runtime, then retry. A replacement video download will not fix a speech dependency error.']);
  if (code === 'speech_unresolved') return help('Some matching words could not be timed.', 'Speech recognition did not locate every expected word and full-subtitle fallback is disabled.', ['Review the audio and subtitle timing. Try the larger fallback speech model before considering full-subtitle muting.']);
  if (code === 'subtitle_missing' || code === 'invalid_subtitles') return help('Usable subtitles were not available.', 'Bleeparr needs readable subtitles with valid timing to locate dialogue for filtering.', ['Add or repair matching subtitles in the selected language, then retry. Check subtitle-provider access if you use automatic downloads.']);
  if (code === 'subtitle_language_mismatch') return help('The subtitles are in a different language.', 'Bleeparr detected a likely language mismatch before creating any output.', ['Replace the selected subtitle with full subtitles in the requested language, then retry. Changing only the filename or language tag does not fix the text.']);
  if (code === 'subtitle_language_uncertain') return help('Subtitle language needs review.', 'There was not enough reliable text to confirm the subtitle language, so processing stopped before creating output.', ['Review the selected subtitle and supply complete text in the requested language, then retry.']);
  if (code === 'subtitle_coverage_suspect') return help('Subtitle coverage needs review.', 'The subtitles contain very little dialogue or leave a large portion of the program uncovered. Quiet scenes and long credits can also cause this warning. No cleaned output was created.', ['Compare the subtitle timing and text with the video. Supply complete, synchronized subtitles and retry when ready. Passing a coverage check does not guarantee every spoken word is represented.']);
  if (code === 'disk_full') return help('There was not enough storage space.', 'Processing could not write a required file.', ['Free space on the temporary-work or output drive, then retry. Check both drives if they are different.']);
  if (code === 'filesystem') return help('A media or work folder could not be accessed.', 'A permission, read-only mount, or storage I/O error prevented processing.', ['Check that the storage is connected and the app can read the input and write to its work/output folders. Fix the reported access problem before retrying.']);
  if (code === 'interrupted') return help('Processing was interrupted.', 'The worker stopped, for example during an app restart.', ['If the status is “Waiting to retry,” processing will be attempted again automatically. Otherwise use Retry when the app is ready.']);
  if (code === 'timeout') return help('Processing exceeded its time limit.', 'The operation did not finish within the allowed time; this alone does not prove the video is damaged.', ['Check whether storage or CPU load is slowing processing. Adjust the time limit or model if needed, then retry.']);
  if (code === 'input_missing' || code === 'input_changed') return help('The input file is missing or changed.', 'The file moved, was replaced, or changed while Bleeparr was preparing or processing it.', ['Wait for downloads or moves to finish, check the media mount, and refresh the library before retrying.']);
  if (code === 'output_exists' || code === 'delivery_failed' || code === 'output_configuration') return help('The cleaned file could not be safely saved.', 'An output conflict, changed file, or destination configuration prevented safe publication. A validated output may already exist; check the details before deleting anything.', ['Review the destination and any existing/staged files. Check the cleaned-file policy and folder permissions. Do not delete either copy until you identify which is valid.']);
  if (code === 'processing' && /non[- ]monotonous dts|non[- ]monotonic/.test(detail)) return help('The video has a timestamp problem.', 'Frame timing moved backward while FFmpeg was writing the video. This can be a container/timing problem without proving the underlying video is corrupt.', ['Try a different release, or have the container repaired and validated before retrying. Repeated retries alone will not repair the timestamps.']);
  if (code === 'worker_exit') return help('The processing worker stopped unexpectedly.', 'The worker exited without a usable result. This log alone does not confirm whether memory, a crash, or another system condition caused it.', ['Check the technical details and server/container logs for the exit reason before retrying.']);
  return help('Processing could not finish.', 'Bleeparr recorded an error, but cannot confidently identify a more specific cause from this message.', ['Expand Technical details for the recorded error. Check the named file, dependency, or setting before retrying; share those details if you need help.']);
}
